country_list = \
    ['Algeria',
     'Australia',
     'Austria',
     'Belgium',
     'Brazil',
     'Canada',
     'China',
     'Denmark',
     'France',
     'Germany',
     'Greece',
     'China Hong Kong SAR',
     'India',
     'Indonesia',
     'Iran',
     'Iraq',
     'Ireland',
     'Israel',
     'Italy',
     'Malaysia',
     'Netherlands',
     'Norway',
     'Peru',
     'Philippines',
     'Poland',
     'Portugal',
     'Russia',
     'South Korea',
     'Spain',
     'Sweden',
     'Switzerland',
     'Turkey',
     'UK',
     'US',
     ]
